Check if argument is a dir or a mount point
rschroll/rmfuse pull request #8
Opened 2021-02-16 09:47 UTC by f3fora

Fuse has errors if trying to mount the file system on an existing mount point or if the path is not a directory or does not exist.
So, rmfuse will mount the file system only if these conditions are fulfilled.

2021-02-17 05:27 UTC, rschroll requested changes
Good thing to check, thanks.

Just some minor changes suggested.

2021-02-17 08:23 UTC, f3fora commented on rmfuse/fuse.py
> +        return
As you request.

2021-02-18 07:34 UTC, rschroll commented on rmfuse/fuse.py
> +
```suggestion

```

2021-02-18 07:49 UTC, rschroll commented
Thanks!  Got it merged in on the command line, since the web UI was being annoying.

2021-02-18 07:49 UTC, closed without merging